
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tpch_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: fivetran_utils
    search_order: ['spark_utils', 'fivetran_utils']
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'fivetran_utils', 'dbt_utils']

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  tpch_demo:
    marts:
      +meterialized: view
    staging:
      +materialized: view
    vault:
      +materialized: table

vars:

  tpch_database: ''
  tpch_schema: 'samples.tpch'

  customers: "{{ source('tpch','customer') }}"
  lineitems: "{{ source('tpch','lineitem') }}"
  nations: "{{ source('tpch','nation') }}"
  orders: "{{ source('tpch','orders') }}"
  parts: "{{ source('tpch','part') }}"
  partsupps: "{{ source('tpch','partsupp') }}"
  regions: "{{ source('tpch','region') }}"
  suppliers: "{{ source('tpch','supplier') }}"

  accounting_periods_pass_through_columns: []
  customers_pass_through_columns: []
  lineitems_pass_through_columns: []
  nations_pass_through_columns: []
  orders_pass_through_columns: []
  parts_pass_through_columns: []
  partsupps_pass_through_columns: []
  regions_pass_through_columns: []
  suppliers_pass_through_columns: []
  
  
